---
- hosts:  "{{ target | default('localhost') }}"
  become: yes
  roles:
    - nodejs

# import playbook to install dependencies and code deploy agent
- import_playbook: install_codedeployagent.yml
