---
# tasks file for helloworld
- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: copying the upstart file
  copy:
    src: hellworld.conf
    dest: /etc/init/helloworld.conf
    owners: root
    group: root
    mode: 0644

- name: starting the helloworld node service
  service:
    name: helloworld
    state: started
